"""add email column

Revision ID: 5e0d3388df34
Revises: 8678775de0b8
Create Date: 2026-04-08 11:09:15.710631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e0d3388df34'
down_revision: Union[str, Sequence[str], None] = '8678775de0b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('name', sa.String(length=50), nullable=True))
    op.add_column('students', sa.Column('email', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'email')
    op.drop_column('students', 'name')
    # ### end Alembic commands ###
